# Generated by Django 5.1 on 2024-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
